gui:
  showCommandLog: false
  showFileTree: true
  theme:
    selectedLineBgColor:
      - reverse
customCommands:
  - key: "C"
    command: "git cz commit"
    context: "files"
    loadingText: "opening commitizen commit tool"
    subprocess: true
